### ISSUE TITLE
Semantic Graph Implementation

### ISSUE THREAD

**Issue by acampesino** [eclipsesource/papyrus-seqd#19]
A implementation of the Semantic dependency graph which each node represents an interaction fragment or other elements used in a interaction.

Nodes can be single node or may group in Clusters. 

Examples of Single nodes are nodes that represent:
- MessageOcurrenceSpecification
- Gates
- ExecutionOcurrenceSpecification
- Or just end / start marks of some fragment.
- Creation and destruction Lifeline marks

And Clusters nodes are groups of nodes. We distinguish two types of clusters, group cluster and fragment cluster.

A Cluster (group Cluster ) contains:
- The fragments enclosed in a ExecutionSpecifications 
- The InteractionFragments of a InteractionOperand in a single lifeline, together with the start and end marks.
- The start and end mark of a InteractionUse in one of the covered lifelines 

And the FragmentCluster contains: 
- All the corrresponding clustersin each of the covered lifelines of a InteractionOperand.
- The fragments corresponding to all the operands of a CombinedFragment
- The clusters with the start and end marks of a InteractionUse
- The nodes and groups defined for a lifeline Lifelines.

The interaction graph provides simple methods to relocate and delete nodes in the graph. 

The nodes are tagged with a slot which represent a vertical position with fragments are located constrained to one single fragment per slot, except for:
- Two endpoints of the same message can be located in the same slot.
- All the start marks in all the lifelines for an InteractionUse / CombinedFragment / InteractionOperand must be in the same slot.
- All the end marks in all the lifelines for an InteractionUse / CombinedFragment / InteractionOperand must be in the same slot.
- The receiveEvent of a message can not be in a Slot located before the one for the sendEvent of the same message
- The start OccurrenceSpecification of an ExecutionSpecification and the ExecutionSpecification itself must be in the same Slot
- The Slot '0' is reserved for the lifeline clusters.

The order and the content of the Slots defines the semantical order. It vertical position (y-coordinate) defined the graphical position.

For a Message end, the x-coordinate is calculated based on the graphical position of the lifeline, the side where its opposite end is located (to the left / to the right) and the execution specification deepness. Special treatment is needed for MessageEnds:
- corresponding to a gate, the graphical constraint defined for that elements are used.
- corresponding to floating point (lost or found MessageEnds), the graphical constraint defined for that elements are used.
- corresponding to a Lifeline creation mark, where the x-coordinate is located in the left side or right side of the lifeline boundary.

So the slot can easily provide the location and boundaries of fragments and groups to be used for validation and for calculating visual feedbacks during the graphical edit operation.

**Comment by acampesino** [comment]
Inital draf implementation: 
Commit [158f6ccc937de748ecc569273ec1d1acb7d6ca78](https://github.com/eclipsesource/papyrus-seqd/commit/158f6ccc937de748ecc569273ec1d1acb7d6ca78)

**Comment by planger** [comment]
As I'm doing a scrub on open issues, we are closing this, as this input has been incorporated into the logical model and dependency graph that we have in the code. Thanks!
