### ISSUE TITLE
[General:003]: Diagram deletion

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#22]
It SHALL be possible to delete the Sequence Diagram itself. This implies at any fragment, message, lifeline, and any of its related elements will be deleted also. Only generic constraints and comments present in the diagram and any other element owned by interaction that is not related to the sequence diagram will be kept.

**Comment by planger** [comment]
@acampesino Just to double-check, we really want to delete all UML elements of the interaction (except for the generic ones) when the diagram is deleted? How does this relate to #23? Should we add an own menu entry for reconstruction rather than deleting the diagram and re-creating one for an existing interaction? Thanks for your feedback!

**Comment by acampesino** [comment]
Yes you are right, it contradicts #23. 
Lets just delete the diagram.

**Comment by planger** [comment]
Thanks for the feedback! I verified that this already works, since it is the default behavior of Papyrus.
