### ISSUE TITLE
[UML Notation:007]: Nested Execution Specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#253]
A nested execution specification SHALL be displayed on top of the enclosing execution specification, centered on one of its sides, the closest to the sent event of the message triggering the execution specification, or the right side if there is no triggering message.

**Comment by rschnekenbu** [comment]
According to a discussion we had with Antonio during a sprint meeting, it is more user friendly if the nested executions are cascading all on the same side. Main reason for that is for the display on nested executions that spans on more than one computer screen. In this latter case, the user may be lost if nesting side changes depending on the message arrival side. Especially if there is a mix of left/right messages, at some point, nested executions would be on same location.

**Comment by rschnekenbu** [comment]
The basic implementation of this requirement has been done. I do not see currently in other milestones what could have an impact on this specification.
