### ISSUE TITLE
[Visual Feedbacks:005]: Forbidden mouse pointer

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#287]
The diagram editor SHALL display the forbidden mouse pointer whenever an edit action cannot be performed, that includes move and reorder actions.

**Comment by rschnekenbu** [comment]
This is ensured by returning unexecutable commands during computation of chain of commands, and then GMF is in charge of displaying the forbidden action. So this requirement is currently implemented by the current runtime/model plugins.
