### ISSUE TITLE
[Lifeline:003]: Create lifeline

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#30]
A lifeline SHALL be created (Palette or assistant) by providing a location (hover point / drag rectangle). The lifeline will be created in that location or the closest possible location in the lifeline header area. Any existing lifeline located on the right side of that location will be shifted towards the right side to make place for the new diagram.

**Comment by cdamus** [comment]
Insertion of a lifeline should make space in the layout by nudging existing lifelines to the right.

**Comment by cdamus** [comment]
Fixed by pull #292.
