### ISSUE TITLE
Centralize all constant min sizes, paddings, etc. in a replaceable component

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#308]
Currently we have a lot of hard-coded integers denoting the min sizes, min distances between fragments, etc. flying around in the figures, edit parts, etc. We should centralize them in a single component that is also replaceable if people would like to customize those.

**Comment by cdamus** [comment]
Yes.  I introduced a pluggable `LayoutConstraints` class that is used (so far) by the `LayoutHelper` (also pluggable) and some edit-parts to deal with a few of these magic numbers.  Perhaps that pattern can be expanded.  Or something new in a similar vein.

**Comment by planger** [comment]
Thanks @tortmayr and @cdamus
