### ISSUE TITLE
Extend #295: Figures, EditParts and Notation Views

### ISSUE THREAD

**Issue by acampesino** [eclipsesource/papyrus-seqd#311]
Adding 3 additional views:
- Figures View: Display the tree hierarchy of Figures for the opened diagram.
- EditParts View: Display the tree hierarchy of EditParts for the opened diagram.
- Notation View: Display the tree hierarchy of Notation Views for the opened diagram.

All the views provide a property sheet displaying the value of class fields. The Views are on synch with the selected object in the diagram editor.

**Comment by planger** [comment]
Closed via #312
