### ISSUE TITLE
Remove unused/obsolete figures

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/papyrus-seqd#317]
Currently the classes InteractionFigureGroup and HeaderFigure are only used in a test project. They seem to be remains from the initial prototyping and are now obsolete.

**Comment by planger** [comment]
@tortmayr Thanks! Can you please open a PR which removes those classes and the demo which uses those classes? Thx!

**Comment by tortmayr** [comment]
@planger  Issue is addressed in #327

**Comment by tortmayr** [comment]
#327 has been merge into master
