### ISSUE TITLE
Sequence Diagram target content resolution error

### ISSUE THREAD

**Issue by tortmayr** [eclipsesource/papyrus-seqd#326]
Currently the Sequence Diagram target cannot be resolved properly because the repository used for Eclipse Orbit is outdated (i.e. not longer existing)

PR #325  addresses this issue

**Comment by tortmayr** [comment]
@planger I thinks this issue is also the reason why the master build fails after your latest merge (b8671fc5b8a126c2509b5dcdd44153abd2b492d6)

**Comment by planger** [comment]
Thanks for the fix! Merged via #325
