### ISSUE TITLE
Add padding for messages

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#339]
Currently messages don't have a padding, thus their shapes and their labels (#251) can overlap.

As specified in #26 we should avoid any overlaps, so we need to add a padding to messages too. This padding should be respected when elements are being
* created: move insertion point downwards if necessary to respect padding and nudge elements below to make room for the message and its padding
* deleted: remove space of message including padding (see also #329)
* moved: elements must not be moved so that the move would cause a semantic inconsistency (see also #331) while still preserving the padding of the moved message and the fragment before or after

The implementation of this requirement for messages itself should be as generic as possible, as any fragments will have paddings (#26). Thus, e.g. querying the padding of other fragments should not be specific to messages.

- [x] Create
- [x] Delete
- [x] Move
- [ ] (To be decided) Compute Message Top Padding based on Font Size

**Comment by cdamus** [comment]
This is finished with the merge of #428 (the move case).  The delete case had already been implemented before.  The accounting for message label size in the padding should be a separate issue.
