### ISSUE TITLE
Nudging doesn't work reliably

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#343]
Given the following interaction:
![image](https://user-images.githubusercontent.com/588090/44973750-e09cec80-af5d-11e8-8225-ae056aa29ead.png)

If we add an action execution on Lifeline1 before the existing execution, we end up with:
![image](https://user-images.githubusercontent.com/588090/44973797-06c28c80-af5e-11e8-8dcb-6803c23308c1.png)

As can be seen on the screenshot, we fail to nudge the elements on Lifeline2. If we would add an execution on Lifeline2, nudging works though.

I've uploaded the project: [Nudgingtest.zip](https://github.com/eclipsesource/papyrus-seqd/files/2344642/Nudgingtest.zip)

**Comment by planger** [comment]
Not sure if this is the same bug, however certainly related to the nudging behavior:
When we delete the execution selected in the interaction below, no nudging is performed.
![image](https://user-images.githubusercontent.com/588090/44974838-1d1e1780-af61-11e8-8534-b13a2f38a0f7.png)

If we delete the execution selected in the screenshot below, nudging is performed.
![image](https://user-images.githubusercontent.com/588090/44974824-14c5dc80-af61-11e8-83e1-bc56ea3a0b42.png)

Imho this seems to be a bug, since it is inconsistent.
[Nudgingtest2.zip](https://github.com/eclipsesource/papyrus-seqd/files/2344709/Nudgingtest2.zip)

**Comment by planger** [comment]
I encountered another instance of unexpected nudging behavior.
If I add a new execution specification as first element on Lifeline2...
![image](https://user-images.githubusercontent.com/588090/44975132-ee547100-af61-11e8-81f2-ae32840f8102.png)

... all messages are nudged, except for the first message.
![image](https://user-images.githubusercontent.com/588090/44975146-fca28d00-af61-11e8-8e55-ad20d1efb707.png)

When deleted again, no nudging (removal of space) is performed at all.
[Nudgingtest3.zip](https://github.com/eclipsesource/papyrus-seqd/files/2344722/Nudgingtest3.zip)

**Comment by cdamus** [comment]
This second part of the disjunction handles the global ordering of fragments in the `Interaction`.  In both the `Interaction` and the `InteractionOperand` metaclasses, the `fragment` association end is *ordered*.  This defines a single comprehensive ordering (in time) of the occurrences that happen in the interaction.  There should be JUnit tests covering this in the `interaction.graph.tests` bundle that will fail without this condition.  (if not, then that's a bug in the test coverage! 😉)

**Comment by planger** [comment]
The issue described in the first comment (https://github.com/eclipsesource/papyrus-seqd/issues/343#issue-356393079) seems to be resolved by #330 too. So the only open issue is the one documented in comment https://github.com/eclipsesource/papyrus-seqd/issues/343#issuecomment-418695991

**Comment by planger** [comment]
Closed via #331
