### ISSUE TITLE
Global ordering when inserting in between sloped messages

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/papyrus-seqd#351]
Inserting an execution after the start but before the end of a sloped async message leads to wrong global ordering of elements in interaction. 

Starting point:
![selection_481](https://user-images.githubusercontent.com/5889696/45478072-62053380-b743-11e8-880f-dde3fd7b1567.png)

Actual:
![selection_482](https://user-images.githubusercontent.com/5889696/45478081-692c4180-b743-11e8-92b4-e63e7f692e11.png)

Expected:
Execution should be inserted after the messageSend but before the messageRecv Event

**Comment by planger** [comment]
Closed via #352
