### ISSUE TITLE
Nudge on Remove: Problem when moving Messages starting Executions

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/papyrus-seqd#358]
Starting point:
![selection_493](https://user-images.githubusercontent.com/5889696/45691280-98361f00-bb58-11e8-84fe-c36882767027.png)

leads to
![selection_494](https://user-images.githubusercontent.com/5889696/45691288-9e2c0000-bb58-11e8-80aa-9dd638d7c257.png)

Problem is that we are creating a nudge command for the message and for the execution resulting in this double move

**Comment by planger** [comment]
Closed via #360
