### ISSUE TITLE
Deletion of create message removes message before and breaks diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#361]
When there is a sync message and a delete message as follows...
![image](https://user-images.githubusercontent.com/588090/45743832-41ceec00-bbfd-11e8-89fb-0bb4abd7791d.png)
... and deleting the delete message, we end up with the following:
![image](https://user-images.githubusercontent.com/588090/45743871-57441600-bbfd-11e8-86a4-b300bacfdefe.png)

As can be seen in the screenshots above, the sync message is deleted from the diagram (even though it shouldn't), but the message still exists in the semantic model (selected in model explorer).

If I try the same scenario with a create message, the diagram breaks entirely:
![image](https://user-images.githubusercontent.com/588090/45743942-8490c400-bbfd-11e8-9aef-48c51eaceb3e.png)
Deleting the delete message leads to:
![image](https://user-images.githubusercontent.com/588090/45743960-92dee000-bbfd-11e8-9104-56b35b3c9a23.png)

**Comment by cdamus** [comment]
It seems that I fixed these deletion scenarios accidentally with changes to the connection attachment handling on *DestructionOccurrenceSpecifications* in commit e092139e5e097904b79225b51a1511bf36447ba9 for issue #59 (the subtask implementing self-destruct messages).
