### ISSUE TITLE
Prohibit invalid delete message creations

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#362]
I can create a delete message from `Lifeline2` to `Lifeline1` between the existing sync message and existing delete messagein the following scenario...
![image](https://user-images.githubusercontent.com/588090/45744130-07b21a00-bbfe-11e8-9a89-a8cf461cefaa.png)
... leading to ...
![image](https://user-images.githubusercontent.com/588090/45744179-2fa17d80-bbfe-11e8-9c73-68bb35a771e7.png)

**Comment by cdamus** [comment]
Sorry, but I actually have a fix for this in the context of my work on self-messages (#59), so I think I'd better re-assign it to myself.  Note that a part of the problem is that the logical model doesn't yet have a representation of destruction occurrence specifications!

**Comment by planger** [comment]
@cdamus Perfect, thanks!
