### ISSUE TITLE
Nudging behavior of elements inserted in execution specifications is unexpected

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#364]
If a message with send event in the execution specification is added, we currently add a lot of space -- different from the behavior we have without execution specifications. Scenario:
![image](https://user-images.githubusercontent.com/588090/45751443-a0eb2b80-bc12-11e8-9316-d6935342a25c.png)
Add a message from within the execution specification to `Lifeline3`:
![image](https://user-images.githubusercontent.com/588090/45751478-b8c2af80-bc12-11e8-9ccb-6c4d5e7bd740.png)
Also, the anchoring of the message seems to be broken.

**Comment by rschnekenbu** [comment]
PR merged, closing issue
