### ISSUE TITLE
Message can be moved from execution specification to another breaking the model/diagram consistency

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#370]
**Steps to reproduce**
1. Create two lifelines
2. Create two executions on second lifeline
3. Create a sync message from first lifeline to second execution start
![image](https://user-images.githubusercontent.com/588090/45942025-0e1b0a00-bfe1-11e8-8888-b169ffddaf72.png)
4. Grab message in the middle and drag it up to the end of first execution
![image](https://user-images.githubusercontent.com/588090/45942044-2559f780-bfe1-11e8-9b50-35bd8ec0a05d.png)

**Actual result**
The connector is moved to the first execution, whereas the semantic model is not correctly up (second execution start is still the message end of the moved message.

**Expected result**
We should disallow moving message ends that are connected to executions.

**Comment by planger** [comment]
Is this one still open or is it resolved with #378? Thanks!

**Comment by cdamus** [comment]
I think it is fixed, yes.  Note that #390 lets us move messages that start or finish an execution, but in that case the execution's start/finish event moves also.
