### ISSUE TITLE
Messages attached to executions should swap sides when lifeline order is changed

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#376]
If there are messages attached to executions (at the border facing towards their send or receive) and you move the lifeline to the other side of the execution, the message end should graphically be swapped so that the message end anchor is always on the side faces the opposite send or receive end.

**Comment by rschnekenbu** [comment]
This one should be also checked with Nested executions.

**Comment by rschnekenbu** [comment]
See PR #405 for implementation

**Comment by rschnekenbu** [comment]
PR Merged on master, closing issue
