### ISSUE TITLE
[Message:005]: Send and receive event alignment constraint

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#38]
When a message has its send, and receive events aligned (same vertical position), this alignment will be always maintained, except for explicitly move or reorder the message end along the lifeline. Under any other circumstance the aligned will be maintained.

**Comment by cdamus** [comment]
I have implemented this constraint in the creation of new messages (synchronous messages always being horizontal and asynchronous messages never going back in time).  I can enforce it after the creation of messages, also.
