### ISSUE TITLE
Create message adds too much vertical space

### ISSUE THREAD

**Issue by cdamus** [eclipsesource/papyrus-seqd#385]
In working on support for re-orienting *create messages* to other lifelines in Issue #52, I observed that the creation of a create message nudges elements down the sequence more than is necessary.  The diagram seems to try to maintain as much space between the head of the lifeline and the first occurrence on it after moving the lifeline head for creation as before, nudging elements on that lifeline (and consequently other lifelines) accordingly:

![nudge-a-lot](https://user-images.githubusercontent.com/1615558/46822398-611eec00-cd59-11e8-8064-7741cc2465b9.gif)

Instead, I think it would be more expected that the occurrences in the sequence only be nudged as far as necessary to maintain the prescribed padding between the lifeline head and the first occurrence on that lifeline (the first after the receive event of the create message, that is).  An implementation of this that is based on the work-in-progress for pull #384 looks like so:

![nudge-as-needed](https://user-images.githubusercontent.com/1615558/46822540-c5da4680-cd59-11e8-90b8-f9b36bfa3bcf.gif)

This makes more sense to me, as it maintains a nice looking layout and acknowledges that the establishment of a create message only moves the lifeline head to where it is supposed to be to indicate when it is created.  Otherwise, the position of the lifeline head is immaterial: if the diagram were rendered with all lifeline heads at the top always, then we would only add as much padding as needed for the create message, itself.  It should be no different when showing the lifeline head at the end of the create message, except that the head has different padding parameters than a message.

**Comment by planger** [comment]
It appears that this issue has not been addressed with #384, has it? At least on current master, the distance between the first fragment and lifeline header on Lifeline2 is maintained when creating a create message.

**Comment by cdamus** [comment]
> It appears that this issue has not been addressed with #384, has it? At least on current master, the distance between the first fragment and lifeline header on Lifeline2 is maintained when creating a create message.

That is correct, @planger.  I have a provisional fix for the problem.  I can dust it off if we want to include it in this milestone.

**Comment by planger** [comment]
@cdamus If it isn't too much work, I think it'd be good, as I also prefer your proposal over the current implementation. Thanks!
