### ISSUE TITLE
[Message:009]: Create Reply Message

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#41]
A reply message SHALL be created (Palette or assistant) by providing the source (send event) and target (receive event) points. The message will be created between these points, or the closest ones than does not contradict any other requirement.

**Comment by planger** [comment]
@acampesino Thanks for taking over this issue! Please note that #330 might be interesting to look at when addressing this issue. Thanks!

**Comment by acampesino** [comment]
As discussed I close it, as it is already possible to create Reply messages.
