### ISSUE TITLE
Resizing or moving an execution without CTRL pressed should nudge elements below

### ISSUE THREAD

**Issue by rschnekenbu** [eclipsesource/papyrus-seqd#430]
Following sprint meeting discussions on 2018-11-29: 
- When resizing down (up) an execution specification, the fragments below that execution specification should be nudged down (up), and not being "nested" as done currently. The CTRL key binding currently allows to disconnect existing ends. This action should be replaced by the nesting or de-nesting of covered/uncovered elements. In general, CTRL key pressed should indicate a semantic reordering, while a CTRL key not pressed should NEVER change the order of the fragments.
Unconnecting message ends like message reply has to be checked if this has some sense towards the specification.

**Comment by planger** [comment]
The same is true for messages (see #48).

**Comment by cdamus** [comment]
I think Pull Request #428 addresses both of these requirements under the aegis of Issue #26.

**Comment by cdamus** [comment]
I can confirm from testing that the changes pending in #428 fix the problem of unintentional reordering of fragments when resizing an execution.

**Comment by cdamus** [comment]
This is fixed with the merge of #428.
