### ISSUE TITLE
Semantic order broken after message move with Ctrl pressed

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#431]
In the project [semantic-order-msg-move.zip](https://github.com/eclipsesource/papyrus-seqd/files/2672308/semantic-order-msg-move.zip) the initial state is as follows:

![image](https://user-images.githubusercontent.com/588090/49878095-1d169900-fe27-11e8-9556-9293e57b6390.png)

the ends `1s` and `1r` denote the send and receive event of the `AsyncMessage1`, respectively. If I now move (with Ctrl pushed) `AsyncMessage1` lower than `AsyncMessage2`, the order of the ends is not updated correctly:

![image](https://user-images.githubusercontent.com/588090/49878202-5222eb80-fe27-11e8-8a20-0109bc2f91f4.png)

This is also partly reproducable when moving up `AsyncMessage2`. Only the send event is re-ordered correctly. But the receive event, isn't.

![image](https://user-images.githubusercontent.com/588090/49878307-88f90180-fe27-11e8-83df-eed47c750976.png)

Note that all works fine for both cases, if we don't move the message, but re-orient the message ends one by one.

**Comment by cdamus** [comment]
I imagine this is closely related to #427, which is a problem of the semantic order being fixed too early, after the send event of a message is updated but before the receive event.
