### ISSUE TITLE
Cannot create sync message with behavior execution

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#433]
When creating a sync message, the popup asking the user which type of execution to create appears, but it only provides one clickable option:
![image](https://user-images.githubusercontent.com/588090/49879665-b72c1080-fe2a-11e8-84a6-2402f8d3423e.png)

Selecting the lower entry (the one that doesn't have a label) skips the creation of the message. Selecting the upper entry (the one which has a label) works fine.

**Comment by cdamus** [comment]
This sounds like #429.

**Comment by planger** [comment]
> This sounds like #429.

Oh, you're right. I missed this one. I'll close this one as a dupe of #429
