### ISSUE TITLE
Cannot move create message

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#437]
Moving async, sync and delete messages works nicely according to the specification (#48). However, we can't move create messages yet.

**Comment by cdamus** [comment]
The test added in commit f17798b06e00c0fb722c1f35dd579913810d5783 does not pass.  It is skipped by an assumption violation, adding 4 skips to the original total of 6 for 10 tests skipped altogether in the suite.

**Comment by cdamus** [comment]
I'll fix the test.
