### ISSUE TITLE
[Message:027]: Messages with Send and Receiving event in the same lifeline

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#59]
When a message has its send, and received events in the same lifeline, the occurrence specification for the send and receive event will keep a predefined distance and the message SHALL displayed with an orthogonal path from send to receive occurrence maintained predefined distance between the vertices of that path. The send and received alignment constraint is not applicable.

**Comment by cdamus** [comment]
Clarification:  for an asynchronous message (call or signal), it can be important that the user be able to separate the receive and send events by a sufficient span to fit other occurrences in the sequence in-between them (on the same or on other lifelines).  Notwithstanding a minimum separation that we can impose for usability.
