### ISSUE TITLE
[Execution Specification:005]: Move the start occurrence of an execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#64]
It SHALL be possible to move the start of the specification without change the fragment order by dragging the top border of the execution specification to a new location. This new location is constrained to be between the previous fragment of the start occurrence, not related to the triggering message, and the next fragment of the execution specification.

Note that start occurrences that are attached to a message end, will move that message end and the message itself if its ends are aligned. Any additional constraint (i.e. send-receive event constraint...) it will also apply.

However, no additional element or fragments SHALL be shift up or down.

**Comment by cdamus** [comment]
Fixed with the merge of pull #404 and pull #414.
