### ISSUE TITLE
[Execution Specification:007]: Move the finish occurrence of an execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#66]
It SHALL be possible to move the finish occurrence of an execution specification without change the fragment order by dragging the bottom border of the execution specification to a new location. This new location is constrained to be between the previous and next fragments of the finish occurrence specification.

Note that finish occurrences that are attached to a message end, will move that message end, and the message itself if its ends are aligned. Any additional constraint (i.e. send-receive event constraint...) it will also apply.

However, no additional element or fragments SHALL be shift up or down.

**Comment by cdamus** [comment]
Fixed with the merge of pull #404 and pull #414.
