### ISSUE TITLE
[Execution Specification:008]: Change the finish occurrence of an execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#67]
It SHALL be possible to reorder the finish occurrence of an execution specification by dragging the bottom border of the execution specification while holding the CTRL key to a new location.

The finish occurrence will be removed from the current position and it will be inserted at the new position. As result it may be fragments that become inside of the execution specification and some that are left out.

The fragment order and the nesting level of execution specifications will be recalculated, and its corresponding visual parts updated accordingly.

If the finish occurrence was attached to a message end, it will be detached, and a new occurrence specification will be used as finish occurrence.

**Comment by cdamus** [comment]
Of course, we need to be careful that on Mac platform it is the Command (⌘) key that is used as the modifier because clicking the mouse while the Ctrl (⌃) key is down invokes the context menu.

**Comment by cdamus** [comment]
Fixed with pull #390.
