### ISSUE TITLE
[Execution Specification:011]: Change the lifeline of an execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#70]
It SHALL be possible to change the execution specification from one lifeline to another by dragging it from one lifeline to another to a new location. The fragments in the lifeline between the start and finish occurrence of the execution specification will be moved to the new lifeline together with the execution specification.

The new location in the target lifeline is constrained by any other applicable constraint (i.e. send-receive event constraint, message alignment, fragment alignment...).

Combined fragments and interaction uses will, instead, remove the original lifeline from the list of covered lifelines and add the new one.

The fragment order and the nesting level of execution specifications will be recalculated, and its corresponding visual parts updated accordingly.

**Comment by cdamus** [comment]
Note that much of this is already implemented in #384 for execution specifications started by messages.  Essentially all that remains to be done after this is the edit-policy allowing the mouse gestures to move the execution to another lifeline.
