### ISSUE TITLE
[Execution Specification:012]: Nested Execution Specifications

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#71]
It SHALL possible to create nested execution specifications. An execution specification is nested when the start and finish occurrence specifications are located between another start and finish occurrences of an execution specification covering the same lifeline. The nested level is defined by counting the number of pair that fulfill that definition.

The nested execution specification SHALL be located center on the left or right side with relation to the enclosing execution specification, depending which side the message that create the execution specification comes from. If the execution specification is not created by a message, the nested execution specification will be centered on the left side.

**Comment by rschnekenbu** [comment]
This one was handled by PR #394.
