### ISSUE TITLE
[Execution Specification:017]: Start of the execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#76]
After a fragment reorder or creation action, a start occurrence ends at the same location (within a predefined margin) of the received event of an asynch or synch message, the receive event occurence will become the start occurrence of the execution specification and the current start occurrence will be deleted.

**Comment by cdamus** [comment]
Connection of a newly created message end to an execution specification was implemented in commit 48c8ae13e48a069d95806504583b134672054ebe for issue #73.  That commit also implements snapping of an existing message end to the start/finish of an existing execution specification when moving the message.  However, it does not in that case replace the execution specification's start/finish occurrence by the message end that was moved.  So, what remains to be done is

- [ ] a message end that is snapped to an execution start/finish when moving the message should replace that start/finish occurrence
- [ ] when moving an execution occurrence up or down the lifeline, it should snap to a message end and when that happens, the start/finish occurrence should be replace by the message end (as appropriate)

**Comment by cdamus** [comment]
Published a new pull request #378 to address the two remaining work items (now checked off in my earlier comment).
