### ISSUE TITLE
[Execution Specification:019]: Execution Specification lifeline constraint

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#78]
The start, finish occurrence specification of an execution specification and the execution specification itself SHALL has the same covered lifeline. In addition, the covered lifeline list of the execution specification must contain only this lifeline and no other one.

**Comment by rschnekenbu** [comment]
This one is ensured in various case (for example SetCoverredCommand) or on creation of the execution. So this issue can be closed.
