### ISSUE TITLE
[Execution Specification:020]: Semantic order in Execution specification

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-seqd#79]
In the fragment order of an interaction or interaction operand:
- The start occurrence of an execution specification SHALL be always before the execution specification and the finish occurrence.
- The execution specification SHALL always be following the start occurrence with no other fragment in between and SHALL always be before the finish occurrence.

**Comment by rschnekenbu** [comment]
This one is ensured by the command creating and manipulating the executions.
